### ISSUE TITLE
Better array syntax

### ISSUE THREAD

**Issue by rurban** [aep/zz#16]
Wouldn't it be much easier to declare arrays like C++ refs, just with constant or variable length for automatic bounds checking, without manual where clause.

Like `&a[2]` or `&a[len]` as signature,and then you also won't need to deref it.

**Comment by aep** [comment]
it actually used to be like that some months ago. (the syntax was bad but basically same idea)
something around:

https://github.com/aep/zz/blob/6e6aba7d4c4f201aba9cc820e7085128bef81120/examples/array/src/main.zz

it's actually very inflexible and doesn't allow return modelling. i.e. a function cannot havea  contract that says "i will work on any array with size N and then return an array with size N+1"

**Comment by aep** [comment]
feel free to repopen if you have more input
