### ISSUE TITLE
zo meny tipos in raedme!11

### ISSUE THREAD

**Issue by pfalcon** [aep/zz#2]
It's always amusing to see people who want to teach us the Right Way to Write Correct Code but don't care enough to run their epiphany thru a spell-checker (text edit box in any contemporary browser is surely accessible to everyone?), or aren't attentive enough to tap that Shift key at the beginning of a sentence.

It's similar to many Rust projects, which have completely down-to-bottom change control policies and commit messages which don't really explain well the changes made. There must be a belief that having some mega-crutches like borrow checker or `thery` (sic! from README) keyword alleviates programmers from any further attentivity or thoroughness - you can do the rest in any sh/tty way and still get a stellar result.

Keep up the great work!

**Comment by aep** [comment]
Glad you're having fun. 

For future reference i'd still like to address some comments which seem to come from experience with the rust community in particular:

I didn't want to be on the hacker news frontpage. I'm happy if it helps others, but I have no intention on teaching anyone "the right way to code" or compete in a popularity contest. 

Its a tool we use at work. It'll eventually be useful for others, but not in it's current state, and that's perfectly fine.
