### ISSUE TITLE
`static_attest` does nothing

### ISSUE THREAD

**Issue by huynhtrankhanh** [aep/zz#29]
This code snippet compiles when it is not supposed to. The `static_attest(A[i] <= max_value);` statement is used to tell the symbolic executor to verify that the `max_value` is indeed the biggest number in the array (it isn't) but ZZ doesn't reject the program as being invalid.
```cpp
export fn main() -> int {
        usize n = 5;
        u64 A[n] = {3, 4, 5, 2, 1};
        u64 mut max_value = A[0];
/*
        for (usize mut i = 1; i < n; i++) {
                if (A[i] > max_value) {
                        max_value = A[i];
                }
        }
*/
        for (usize mut i = 0; i < n; i++) {
                static_attest(A[i] <= max_value);
        }
        return 0;
}
```

**Comment by huynhtrankhanh** [comment]
Oops, turns out `static_attest` does not do what I think it does. Sorry. But maybe you could document its usage somewhere.

**Comment by aep** [comment]
glad you figured it out, could you let me know what you thought it does?

**Comment by huynhtrankhanh** [comment]
I thought it would statically check the assertion I made using the SMT
solver.
