### ISSUE TITLE
Allow search path to be extended with environment variable

### ISSUE THREAD

**Issue by jwerle** [aep/zz#37]
Hi @aep,

What are your thoughts on allowing one the ability to add a path to the [search paths](https://github.com/aep/zz/blob/master/src/lib.rs#L86) `HashSet` with an environment variable? This could allow users to specify the location of their modules if they are not located in [standard directories](https://github.com/aep/zz/blob/master/src/lib.rs#L87-L96) when running `zz`:

```sh
$ ZZ_PATH=./path/to/modules zz build
```

I think something like:

```rust
if let Ok(zz_path) = std::env::var("ZZ_MODULES_PATH") {
	let module_paths = zz_path.split(":");
	for path in module_paths {
		searchpaths.insert(std::path::Path::new(&path).to_path_buf());
	}
} 
```

**Comment by aep** [comment]
Yes this is a good idea, thanks for the suggestion

**Comment by jwerle** [comment]
Great! I issued an initial implementation in a PR (#38)
