### ISSUE TITLE
change name to zzz

### ISSUE THREAD

**Issue by cris691** [aep/zz#4]
because it's more type safe

**Comment by aep** [comment]
I don't get the joke.

**Comment by tech6hutch** [comment]
It would make the language sound like a snooze

**Comment by cris691** [comment]
it's ambiguously ambiguous as we don't know if the z is derefencing itself or the other z
is zz z(z) or (z)z, or the double-z operator? perhaps a single z is better. 

but i think the triple-z has the advantage that it's definitively ambiguous. there's no way we can resolve what it references, so it's a clearer ambiguity than the current name, and therefore should be preferred.

**Comment by rofl0r** [comment]
https://github.com/void-linux/void-runit/blob/master/zzz.8

**Comment by aep** [comment]
Unfortunately now that it's all over the internet, changing the name isn't reasonably anyway.
