### ISSUE TITLE
Why is heap allocation discouraged?

### ISSUE THREAD

**Issue by richardanaya** [aep/zz#51]
Is there some fundamental limitation of zz not being mentioned in the readme?

**Comment by aep** [comment]
zz is built for non-heap environments. specifically embedded (or wasm, as we just learned)
you can call malloc, but none of the tools are built for it, and the prover probably falls on its nose.

the reason this lacks documentation is really that in embedded you don't do malloc anyway, so i assumed most people know

**Comment by richardanaya** [comment]
I see! I feel like what would be really interesting to see would be an easy way for making global fixed capacity vectors to help play to `zz`'s strengths :)

**Comment by aep** [comment]
create a string with 200 bytes capacity:

```C++
new+200 a = string::empty();
```

create a generic allocator pool with 200 bytes capacity and slab size of 16 bytes

```C++
new+200 a = pool::make(16);
```

**Comment by aep** [comment]
happy to answer any questions you have on github issues :)
